### ISSUE TITLE
Behavior Not Proper

### ISSUE THREAD

**Issue by PrinceDholakiya** [florent37/SingleDateAndDayPicker#134]
![screenshot_2018-05-24-19-27-13](https://user-images.githubusercontent.com/39218065/40491350-acfb3b2e-5f22-11e8-8b86-99584f7ceca8.png)

**See the above picture**, model of this device is nexus 
**"OK" button** of this library is show behind minimize button
This problem is only within the navigation-compatible device.
i hope you solve this issues (problem).

Tell the solution of this problem : **E-mail address** : - princedholakiya6319@gmail.com

=========================================================

Code : 

public void showDatePicker() {

        if (datePickerDialog != null) {
            if (datePickerDialog.isDisplaying()) {
                return;
            }
        }

        DoubleDateAndTimePickerDialog.Listener listener = this::setDateTime;

        datePickerDialog =
                new DoubleDateAndTimePickerDialog.Builder(getActivity())
                        .title("Select date & time")
                        .tab0Text("Start")
                        .tab1Text("End")
                        .mustBeOnFuture()
                        .titleTextColor(getActivity().getResources().getColor(R.color.grey_900))
                        .mainColor(getActivity().getResources().getColor(R.color.colorPrimaryDark))
                        .backgroundColor(getActivity().getResources().getColor(R.color.grey_900))
                        .bottomSheet()
                        .curved()
                        .listener(listener)
                        .build();

        datePickerDialog.display();
    }

**Comment by leonardogazio** [comment]
Hey guys, is there already a solution for that issue?
