### ISSUE TITLE
Getting Error in Project Sync Android studio

### ISSUE THREAD

**Issue by Maree27** [florent37/SingleDateAndDayPicker#229]
Here is the screen shot of what i am getting after i sync project
![img](https://user-images.githubusercontent.com/52140230/63768295-b508c580-c884-11e9-8878-e326bda255e6.PNG)

**Comment by dimabran** [comment]
Try using the most recent version
`    implementation 'com.github.florent37:singledateandtimepicker:2.1.5'`
